### ISSUE TITLE
Dynamic expandoobject 

### ISSUE THREAD

**Issue by Jonalex9020** [finalbeta/GLPI.NET#3]
Hello, 

When i try to use 

foreach (dynamic data in ((dynamic)responseObj).result.active_entity.active_entities)
{

I've got an error : one or more types required to compile à dynamic expression cannot beaucoup found 

Have you got an idea why IT doesn't work ? 

Thanks for your answer and thanks for Your contribution

**Comment by finalbeta** [comment]
Hi Jonalex, please have a look at https://blogs.msdn.microsoft.com/pradeepsvs/2014/09/16/one-or-more-types-required-to-compile-a-dynamic-expression-cannot-be-found/
I believe it might solve that for you.

**Comment by Jonalex9020** [comment]
Hello !

It works perfectly, thanks for your answer !!
